/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypeName } from './TypeName';
import {
    TypeNameFromJSON,
    TypeNameFromJSONTyped,
    TypeNameToJSON,
    TypeNameToJSONTyped,
} from './TypeName';
import type { TimelineResult } from './TimelineResult';
import {
    TimelineResultFromJSON,
    TimelineResultFromJSONTyped,
    TimelineResultToJSON,
    TimelineResultToJSONTyped,
} from './TimelineResult';

/**
 * 
 * @export
 * @interface AboutCommunityResult
 */
export interface AboutCommunityResult {
    /**
     * 
     * @type {TypeName}
     * @memberof AboutCommunityResult
     */
    typename: TypeName;
    /**
     * 
     * @type {TimelineResult}
     * @memberof AboutCommunityResult
     */
    aboutTimeline: TimelineResult;
}



/**
 * Check if a given object implements the AboutCommunityResult interface.
 */
export function instanceOfAboutCommunityResult(value: object): value is AboutCommunityResult {
    if (!('typename' in value) || value['typename'] === undefined) return false;
    if (!('aboutTimeline' in value) || value['aboutTimeline'] === undefined) return false;
    return true;
}

export function AboutCommunityResultFromJSON(json: any): AboutCommunityResult {
    return AboutCommunityResultFromJSONTyped(json, false);
}

export function AboutCommunityResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AboutCommunityResult {
    if (json == null) {
        return json;
    }
    return {
        
        'typename': TypeNameFromJSON(json['__typename']),
        'aboutTimeline': TimelineResultFromJSON(json['about_timeline']),
    };
}

export function AboutCommunityResultToJSON(json: any): AboutCommunityResult {
    return AboutCommunityResultToJSONTyped(json, false);
}

export function AboutCommunityResultToJSONTyped(value?: AboutCommunityResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '__typename': TypeNameToJSON(value['typename']),
        'about_timeline': TimelineResultToJSON(value['aboutTimeline']),
    };
}

