/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdditionalMediaInfoCallToActionsUrl
 */
export interface AdditionalMediaInfoCallToActionsUrl {
    /**
     * 
     * @type {string}
     * @memberof AdditionalMediaInfoCallToActionsUrl
     */
    url: string;
}

/**
 * Check if a given object implements the AdditionalMediaInfoCallToActionsUrl interface.
 */
export function instanceOfAdditionalMediaInfoCallToActionsUrl(value: object): boolean {
    if (!('url' in value)) return false;
    return true;
}

export function AdditionalMediaInfoCallToActionsUrlFromJSON(json: any): AdditionalMediaInfoCallToActionsUrl {
    return AdditionalMediaInfoCallToActionsUrlFromJSONTyped(json, false);
}

export function AdditionalMediaInfoCallToActionsUrlFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdditionalMediaInfoCallToActionsUrl {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
    };
}

export function AdditionalMediaInfoCallToActionsUrlToJSON(value?: AdditionalMediaInfoCallToActionsUrl | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
    };
}

