/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleResult } from './ArticleResult';
import {
    ArticleResultFromJSON,
    ArticleResultFromJSONTyped,
    ArticleResultToJSON,
} from './ArticleResult';

/**
 * 
 * @export
 * @interface ArticleResults
 */
export interface ArticleResults {
    /**
     * 
     * @type {ArticleResult}
     * @memberof ArticleResults
     */
    result: ArticleResult;
}

/**
 * Check if a given object implements the ArticleResults interface.
 */
export function instanceOfArticleResults(value: object): value is ArticleResults {
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function ArticleResultsFromJSON(json: any): ArticleResults {
    return ArticleResultsFromJSONTyped(json, false);
}

export function ArticleResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleResults {
    if (json == null) {
        return json;
    }
    return {
        
        'result': ArticleResultFromJSON(json['result']),
    };
}

export function ArticleResultsToJSON(value?: ArticleResults | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'result': ArticleResultToJSON(value['result']),
    };
}

