/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Timeline } from './Timeline';
import {
    TimelineFromJSON,
    TimelineFromJSONTyped,
    TimelineToJSON,
    TimelineToJSONTyped,
} from './Timeline';

/**
 * 
 * @export
 * @interface BookmarksTimeline
 */
export interface BookmarksTimeline {
    /**
     * 
     * @type {Timeline}
     * @memberof BookmarksTimeline
     */
    timeline: Timeline;
}

/**
 * Check if a given object implements the BookmarksTimeline interface.
 */
export function instanceOfBookmarksTimeline(value: object): value is BookmarksTimeline {
    if (!('timeline' in value) || value['timeline'] === undefined) return false;
    return true;
}

export function BookmarksTimelineFromJSON(json: any): BookmarksTimeline {
    return BookmarksTimelineFromJSONTyped(json, false);
}

export function BookmarksTimelineFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookmarksTimeline {
    if (json == null) {
        return json;
    }
    return {
        
        'timeline': TimelineFromJSON(json['timeline']),
    };
}

export function BookmarksTimelineToJSON(json: any): BookmarksTimeline {
    return BookmarksTimelineToJSONTyped(json, false);
}

export function BookmarksTimelineToJSONTyped(value?: BookmarksTimeline | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timeline': TimelineToJSON(value['timeline']),
    };
}

