/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookmarksTimeline } from './BookmarksTimeline';
import {
    BookmarksTimelineFromJSON,
    BookmarksTimelineFromJSONTyped,
    BookmarksTimelineToJSON,
    BookmarksTimelineToJSONTyped,
} from './BookmarksTimeline';

/**
 * 
 * @export
 * @interface BookmarksResponseData
 */
export interface BookmarksResponseData {
    /**
     * 
     * @type {BookmarksTimeline}
     * @memberof BookmarksResponseData
     */
    bookmarkTimelineV2: BookmarksTimeline;
}

/**
 * Check if a given object implements the BookmarksResponseData interface.
 */
export function instanceOfBookmarksResponseData(value: object): value is BookmarksResponseData {
    if (!('bookmarkTimelineV2' in value) || value['bookmarkTimelineV2'] === undefined) return false;
    return true;
}

export function BookmarksResponseDataFromJSON(json: any): BookmarksResponseData {
    return BookmarksResponseDataFromJSONTyped(json, false);
}

export function BookmarksResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookmarksResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'bookmarkTimelineV2': BookmarksTimelineFromJSON(json['bookmark_timeline_v2']),
    };
}

export function BookmarksResponseDataToJSON(json: any): BookmarksResponseData {
    return BookmarksResponseDataToJSONTyped(json, false);
}

export function BookmarksResponseDataToJSONTyped(value?: BookmarksResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bookmark_timeline_v2': BookmarksTimelineToJSON(value['bookmarkTimelineV2']),
    };
}

