/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MediaCommunityTweetData } from './MediaCommunityTweetData';
import {
    MediaCommunityTweetDataFromJSON,
    MediaCommunityTweetDataFromJSONTyped,
    MediaCommunityTweetDataToJSON,
    MediaCommunityTweetDataToJSONTyped,
} from './MediaCommunityTweetData';
import type { ErrorResponse } from './ErrorResponse';
import {
    ErrorResponseFromJSON,
    ErrorResponseFromJSONTyped,
    ErrorResponseToJSON,
    ErrorResponseToJSONTyped,
} from './ErrorResponse';

/**
 * 
 * @export
 * @interface CommunityMediaTimelineResponse
 */
export interface CommunityMediaTimelineResponse {
    /**
     * 
     * @type {MediaCommunityTweetData}
     * @memberof CommunityMediaTimelineResponse
     */
    data: MediaCommunityTweetData;
    /**
     * 
     * @type {Array<ErrorResponse>}
     * @memberof CommunityMediaTimelineResponse
     */
    errors?: Array<ErrorResponse>;
}

/**
 * Check if a given object implements the CommunityMediaTimelineResponse interface.
 */
export function instanceOfCommunityMediaTimelineResponse(value: object): value is CommunityMediaTimelineResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CommunityMediaTimelineResponseFromJSON(json: any): CommunityMediaTimelineResponse {
    return CommunityMediaTimelineResponseFromJSONTyped(json, false);
}

export function CommunityMediaTimelineResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommunityMediaTimelineResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': MediaCommunityTweetDataFromJSON(json['data']),
        'errors': json['errors'] == null ? undefined : ((json['errors'] as Array<any>).map(ErrorResponseFromJSON)),
    };
}

export function CommunityMediaTimelineResponseToJSON(json: any): CommunityMediaTimelineResponse {
    return CommunityMediaTimelineResponseToJSONTyped(json, false);
}

export function CommunityMediaTimelineResponseToJSONTyped(value?: CommunityMediaTimelineResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': MediaCommunityTweetDataToJSON(value['data']),
        'errors': value['errors'] == null ? undefined : ((value['errors'] as Array<any>).map(ErrorResponseToJSON)),
    };
}

