/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommunityRule
 */
export interface CommunityRule {
    /**
     * 
     * @type {string}
     * @memberof CommunityRule
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CommunityRule
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CommunityRule
     */
    restId: string;
}

/**
 * Check if a given object implements the CommunityRule interface.
 */
export function instanceOfCommunityRule(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "restId" in value;

    return isInstance;
}

export function CommunityRuleFromJSON(json: any): CommunityRule {
    return CommunityRuleFromJSONTyped(json, false);
}

export function CommunityRuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommunityRule {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'name': json['name'],
        'restId': json['rest_id'],
    };
}

export function CommunityRuleToJSON(value?: CommunityRule | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'name': value.name,
        'rest_id': value.restId,
    };
}

