/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypeName } from './TypeName';
import {
    TypeNameFromJSON,
    TypeNameFromJSONTyped,
    TypeNameToJSON,
} from './TypeName';

/**
 * 
 * @export
 * @interface CommunityJoinActionResult
 */
export interface CommunityJoinActionResult {
    /**
     * 
     * @type {TypeName}
     * @memberof CommunityJoinActionResult
     */
    typename: TypeName;
}



/**
 * Check if a given object implements the CommunityJoinActionResult interface.
 */
export function instanceOfCommunityJoinActionResult(value: object): value is CommunityJoinActionResult {
    if (!('typename' in value) || value['typename'] === undefined) return false;
    return true;
}

export function CommunityJoinActionResultFromJSON(json: any): CommunityJoinActionResult {
    return CommunityJoinActionResultFromJSONTyped(json, false);
}

export function CommunityJoinActionResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommunityJoinActionResult {
    if (json == null) {
        return json;
    }
    return {
        
        'typename': TypeNameFromJSON(json['__typename']),
    };
}

export function CommunityJoinActionResultToJSON(value?: CommunityJoinActionResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        '__typename': TypeNameToJSON(value['typename']),
    };
}

