/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TimelineTimelineCursor } from './TimelineTimelineCursor';
import {
    instanceOfTimelineTimelineCursor,
    TimelineTimelineCursorFromJSON,
    TimelineTimelineCursorFromJSONTyped,
    TimelineTimelineCursorToJSON,
} from './TimelineTimelineCursor';
import type { TimelineTimelineItem } from './TimelineTimelineItem';
import {
    instanceOfTimelineTimelineItem,
    TimelineTimelineItemFromJSON,
    TimelineTimelineItemFromJSONTyped,
    TimelineTimelineItemToJSON,
} from './TimelineTimelineItem';
import type { TimelineTimelineModule } from './TimelineTimelineModule';
import {
    instanceOfTimelineTimelineModule,
    TimelineTimelineModuleFromJSON,
    TimelineTimelineModuleFromJSONTyped,
    TimelineTimelineModuleToJSON,
} from './TimelineTimelineModule';

/**
 * @type ContentUnion
 * 
 * @export
 */
export type ContentUnion = { entryType: 'TimelineTimelineCursor' } & TimelineTimelineCursor | { entryType: 'TimelineTimelineItem' } & TimelineTimelineItem | { entryType: 'TimelineTimelineModule' } & TimelineTimelineModule;

export function ContentUnionFromJSON(json: any): ContentUnion {
    return ContentUnionFromJSONTyped(json, false);
}

export function ContentUnionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentUnion {
    if (json == null) {
        return json;
    }
    switch (json['entryType']) {
        case 'TimelineTimelineCursor':
            return {...TimelineTimelineCursorFromJSONTyped(json, true), entryType: 'TimelineTimelineCursor'};
        case 'TimelineTimelineItem':
            return {...TimelineTimelineItemFromJSONTyped(json, true), entryType: 'TimelineTimelineItem'};
        case 'TimelineTimelineModule':
            return {...TimelineTimelineModuleFromJSONTyped(json, true), entryType: 'TimelineTimelineModule'};
        default:
            throw new Error(`No variant of ContentUnion exists with 'entryType=${json['entryType']}'`);
    }
}

export function ContentUnionToJSON(value?: ContentUnion | null): any {
    if (value == null) {
        return value;
    }
    switch (value['entryType']) {
        case 'TimelineTimelineCursor':
            return TimelineTimelineCursorToJSON(value);
        case 'TimelineTimelineItem':
            return TimelineTimelineItemToJSON(value);
        case 'TimelineTimelineModule':
            return TimelineTimelineModuleToJSON(value);
        default:
            throw new Error(`No variant of ContentUnion exists with 'entryType=${value['entryType']}'`);
    }

}

