/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateRetweet } from './CreateRetweet';
import {
    CreateRetweetFromJSON,
    CreateRetweetFromJSONTyped,
    CreateRetweetToJSON,
} from './CreateRetweet';

/**
 * 
 * @export
 * @interface CreateRetweetResponseResult
 */
export interface CreateRetweetResponseResult {
    /**
     * 
     * @type {CreateRetweet}
     * @memberof CreateRetweetResponseResult
     */
    retweetResults: CreateRetweet;
}

/**
 * Check if a given object implements the CreateRetweetResponseResult interface.
 */
export function instanceOfCreateRetweetResponseResult(value: object): value is CreateRetweetResponseResult {
    if (!('retweetResults' in value) || value['retweetResults'] === undefined) return false;
    return true;
}

export function CreateRetweetResponseResultFromJSON(json: any): CreateRetweetResponseResult {
    return CreateRetweetResponseResultFromJSONTyped(json, false);
}

export function CreateRetweetResponseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRetweetResponseResult {
    if (json == null) {
        return json;
    }
    return {
        
        'retweetResults': CreateRetweetFromJSON(json['retweet_results']),
    };
}

export function CreateRetweetResponseResultToJSON(value?: CreateRetweetResponseResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'retweet_results': CreateRetweetToJSON(value['retweetResults']),
    };
}

