/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DisplayType = {
    Vertical: 'Vertical',
    VerticalConversation: 'VerticalConversation',
    VerticalGrid: 'VerticalGrid',
    Carousel: 'Carousel'
} as const;
export type DisplayType = typeof DisplayType[keyof typeof DisplayType];


export function instanceOfDisplayType(value: any): boolean {
    for (const key in DisplayType) {
        if (Object.prototype.hasOwnProperty.call(DisplayType, key)) {
            if (DisplayType[key as keyof typeof DisplayType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DisplayTypeFromJSON(json: any): DisplayType {
    return DisplayTypeFromJSONTyped(json, false);
}

export function DisplayTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DisplayType {
    return json as DisplayType;
}

export function DisplayTypeToJSON(value?: DisplayType | null): any {
    return value as any;
}

export function DisplayTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): DisplayType {
    return value as DisplayType;
}

