/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorsData } from './ErrorsData';
import {
    ErrorsDataFromJSON,
    ErrorsDataFromJSONTyped,
    ErrorsDataToJSON,
} from './ErrorsData';

/**
 * 
 * @export
 * @interface Errors
 */
export interface Errors {
    /**
     * 
     * @type {ErrorsData}
     * @memberof Errors
     */
    data?: ErrorsData;
    /**
     * 
     * @type {Array<Error>}
     * @memberof Errors
     */
    errors: Array<Error>;
}

/**
 * Check if a given object implements the Errors interface.
 */
export function instanceOfErrors(value: object): value is Errors {
    if (!('errors' in value) || value['errors'] === undefined) return false;
    return true;
}

export function ErrorsFromJSON(json: any): Errors {
    return ErrorsFromJSONTyped(json, false);
}

export function ErrorsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Errors {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ErrorsDataFromJSON(json['data']),
        'errors': json['errors'],
    };
}

export function ErrorsToJSON(value?: Errors | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': ErrorsDataToJSON(value['data']),
        'errors': value['errors'],
    };
}

