/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FavoriteTweet
 */
export interface FavoriteTweet {
    /**
     * 
     * @type {string}
     * @memberof FavoriteTweet
     */
    favoriteTweet: string;
}

/**
 * Check if a given object implements the FavoriteTweet interface.
 */
export function instanceOfFavoriteTweet(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "favoriteTweet" in value;

    return isInstance;
}

export function FavoriteTweetFromJSON(json: any): FavoriteTweet {
    return FavoriteTweetFromJSONTyped(json, false);
}

export function FavoriteTweetFromJSONTyped(json: any, ignoreDiscriminator: boolean): FavoriteTweet {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'favoriteTweet': json['favorite_tweet'],
    };
}

export function FavoriteTweetToJSON(value?: FavoriteTweet | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'favorite_tweet': value.favoriteTweet,
    };
}

