/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FollowTimeline } from './FollowTimeline';
import {
    FollowTimelineFromJSON,
    FollowTimelineFromJSONTyped,
    FollowTimelineToJSON,
} from './FollowTimeline';
import type { TypeName } from './TypeName';
import {
    TypeNameFromJSON,
    TypeNameFromJSONTyped,
    TypeNameToJSON,
} from './TypeName';

/**
 * 
 * @export
 * @interface FollowResponseResult
 */
export interface FollowResponseResult {
    /**
     * 
     * @type {TypeName}
     * @memberof FollowResponseResult
     */
    typename: TypeName;
    /**
     * 
     * @type {FollowTimeline}
     * @memberof FollowResponseResult
     */
    timeline: FollowTimeline;
}

/**
 * Check if a given object implements the FollowResponseResult interface.
 */
export function instanceOfFollowResponseResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "typename" in value;
    isInstance = isInstance && "timeline" in value;

    return isInstance;
}

export function FollowResponseResultFromJSON(json: any): FollowResponseResult {
    return FollowResponseResultFromJSONTyped(json, false);
}

export function FollowResponseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): FollowResponseResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'typename': TypeNameFromJSON(json['__typename']),
        'timeline': FollowTimelineFromJSON(json['timeline']),
    };
}

export function FollowResponseResultToJSON(value?: FollowResponseResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '__typename': TypeNameToJSON(value.typename),
        'timeline': FollowTimelineToJSON(value.timeline),
    };
}

