/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Timeline } from './Timeline';
import {
    TimelineFromJSON,
    TimelineFromJSONTyped,
    TimelineToJSON,
    TimelineToJSONTyped,
} from './Timeline';

/**
 * 
 * @export
 * @interface FollowTimeline
 */
export interface FollowTimeline {
    /**
     * 
     * @type {Timeline}
     * @memberof FollowTimeline
     */
    timeline: Timeline;
}

/**
 * Check if a given object implements the FollowTimeline interface.
 */
export function instanceOfFollowTimeline(value: object): value is FollowTimeline {
    if (!('timeline' in value) || value['timeline'] === undefined) return false;
    return true;
}

export function FollowTimelineFromJSON(json: any): FollowTimeline {
    return FollowTimelineFromJSONTyped(json, false);
}

export function FollowTimelineFromJSONTyped(json: any, ignoreDiscriminator: boolean): FollowTimeline {
    if (json == null) {
        return json;
    }
    return {
        
        'timeline': TimelineFromJSON(json['timeline']),
    };
}

export function FollowTimelineToJSON(json: any): FollowTimeline {
    return FollowTimelineToJSONTyped(json, false);
}

export function FollowTimelineToJSONTyped(value?: FollowTimeline | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timeline': TimelineToJSON(value['timeline']),
    };
}

