/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FollowResponseUser } from './FollowResponseUser';
import {
    FollowResponseUserFromJSON,
    FollowResponseUserFromJSONTyped,
    FollowResponseUserToJSON,
    FollowResponseUserToJSONTyped,
} from './FollowResponseUser';

/**
 * 
 * @export
 * @interface FollowResponseData
 */
export interface FollowResponseData {
    /**
     * 
     * @type {FollowResponseUser}
     * @memberof FollowResponseData
     */
    user?: FollowResponseUser;
}

/**
 * Check if a given object implements the FollowResponseData interface.
 */
export function instanceOfFollowResponseData(value: object): value is FollowResponseData {
    return true;
}

export function FollowResponseDataFromJSON(json: any): FollowResponseData {
    return FollowResponseDataFromJSONTyped(json, false);
}

export function FollowResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): FollowResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'] == null ? undefined : FollowResponseUserFromJSON(json['user']),
    };
}

export function FollowResponseDataToJSON(json: any): FollowResponseData {
    return FollowResponseDataToJSONTyped(json, false);
}

export function FollowResponseDataToJSONTyped(value?: FollowResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': FollowResponseUserToJSON(value['user']),
    };
}

