/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Errors,
    instanceOfErrors,
    ErrorsFromJSON,
    ErrorsFromJSONTyped,
    ErrorsToJSON,
} from './Errors';
import {
    TweetRetweetersResponse,
    instanceOfTweetRetweetersResponse,
    TweetRetweetersResponseFromJSON,
    TweetRetweetersResponseFromJSONTyped,
    TweetRetweetersResponseToJSON,
} from './TweetRetweetersResponse';

/**
 * @type GetRetweeters200Response
 * 
 * @export
 */
export type GetRetweeters200Response = Errors | TweetRetweetersResponse;

export function GetRetweeters200ResponseFromJSON(json: any): GetRetweeters200Response {
    return GetRetweeters200ResponseFromJSONTyped(json, false);
}

export function GetRetweeters200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetRetweeters200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...ErrorsFromJSONTyped(json, true), ...TweetRetweetersResponseFromJSONTyped(json, true) };
}

export function GetRetweeters200ResponseToJSON(value?: GetRetweeters200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfErrors(value)) {
        return ErrorsToJSON(value as Errors);
    }
    if (instanceOfTweetRetweetersResponse(value)) {
        return TweetRetweetersResponseToJSON(value as TweetRetweetersResponse);
    }

    return {};
}

