/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GrokShareAttachmentItem } from './GrokShareAttachmentItem';
import {
    GrokShareAttachmentItemFromJSON,
    GrokShareAttachmentItemFromJSONTyped,
    GrokShareAttachmentItemToJSON,
    GrokShareAttachmentItemToJSONTyped,
} from './GrokShareAttachmentItem';

/**
 * 
 * @export
 * @interface GrokShareAttachment
 */
export interface GrokShareAttachment {
    /**
     * 
     * @type {Array<GrokShareAttachmentItem>}
     * @memberof GrokShareAttachment
     */
    items: Array<GrokShareAttachmentItem>;
}

/**
 * Check if a given object implements the GrokShareAttachment interface.
 */
export function instanceOfGrokShareAttachment(value: object): value is GrokShareAttachment {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function GrokShareAttachmentFromJSON(json: any): GrokShareAttachment {
    return GrokShareAttachmentFromJSONTyped(json, false);
}

export function GrokShareAttachmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): GrokShareAttachment {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(GrokShareAttachmentItemFromJSON)),
    };
}

export function GrokShareAttachmentToJSON(json: any): GrokShareAttachment {
    return GrokShareAttachmentToJSONTyped(json, false);
}

export function GrokShareAttachmentToJSONTyped(value?: GrokShareAttachment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(GrokShareAttachmentItemToJSON)),
    };
}

