/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    TimelineAddEntries,
    instanceOfTimelineAddEntries,
    TimelineAddEntriesFromJSON,
    TimelineAddEntriesFromJSONTyped,
    TimelineAddEntriesToJSON,
} from './TimelineAddEntries';
import {
    TimelineClearCache,
    instanceOfTimelineClearCache,
    TimelineClearCacheFromJSON,
    TimelineClearCacheFromJSONTyped,
    TimelineClearCacheToJSON,
} from './TimelineClearCache';
import {
    TimelinePinEntry,
    instanceOfTimelinePinEntry,
    TimelinePinEntryFromJSON,
    TimelinePinEntryFromJSONTyped,
    TimelinePinEntryToJSON,
} from './TimelinePinEntry';
import {
    TimelineTerminateTimeline,
    instanceOfTimelineTerminateTimeline,
    TimelineTerminateTimelineFromJSON,
    TimelineTerminateTimelineFromJSONTyped,
    TimelineTerminateTimelineToJSON,
} from './TimelineTerminateTimeline';

/**
 * @type InstructionUnion
 * 
 * @export
 */
export type InstructionUnion = { type: 'TimelineAddEntries' } & TimelineAddEntries | { type: 'TimelineClearCache' } & TimelineClearCache | { type: 'TimelinePinEntry' } & TimelinePinEntry | { type: 'TimelineTerminateTimeline' } & TimelineTerminateTimeline;

export function InstructionUnionFromJSON(json: any): InstructionUnion {
    return InstructionUnionFromJSONTyped(json, false);
}

export function InstructionUnionFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstructionUnion {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['type']) {
        case 'TimelineAddEntries':
            return {...TimelineAddEntriesFromJSONTyped(json, true), type: 'TimelineAddEntries'};
        case 'TimelineClearCache':
            return {...TimelineClearCacheFromJSONTyped(json, true), type: 'TimelineClearCache'};
        case 'TimelinePinEntry':
            return {...TimelinePinEntryFromJSONTyped(json, true), type: 'TimelinePinEntry'};
        case 'TimelineTerminateTimeline':
            return {...TimelineTerminateTimelineFromJSONTyped(json, true), type: 'TimelineTerminateTimeline'};
        default:
            throw new Error(`No variant of InstructionUnion exists with 'type=${json['type']}'`);
    }
}

export function InstructionUnionToJSON(value?: InstructionUnion | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['type']) {
        case 'TimelineAddEntries':
            return TimelineAddEntriesToJSON(value);
        case 'TimelineClearCache':
            return TimelineClearCacheToJSON(value);
        case 'TimelinePinEntry':
            return TimelinePinEntryToJSON(value);
        case 'TimelineTerminateTimeline':
            return TimelineTerminateTimelineToJSON(value);
        default:
            throw new Error(`No variant of InstructionUnion exists with 'type=${value['type']}'`);
    }

}

