/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TweetUnion } from './TweetUnion';
import {
    TweetUnionFromJSON,
    TweetUnionFromJSONTyped,
    TweetUnionToJSON,
} from './TweetUnion';
import type { TypeName } from './TypeName';
import {
    TypeNameFromJSON,
    TypeNameFromJSONTyped,
    TypeNameToJSON,
} from './TypeName';

/**
 * 
 * @export
 * @interface ItemResult
 */
export interface ItemResult {
    /**
     * 
     * @type {TypeName}
     * @memberof ItemResult
     */
    typename?: TypeName;
    /**
     * 
     * @type {TweetUnion}
     * @memberof ItemResult
     */
    result?: TweetUnion;
}

/**
 * Check if a given object implements the ItemResult interface.
 */
export function instanceOfItemResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ItemResultFromJSON(json: any): ItemResult {
    return ItemResultFromJSONTyped(json, false);
}

export function ItemResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'typename': !exists(json, '__typename') ? undefined : TypeNameFromJSON(json['__typename']),
        'result': !exists(json, 'result') ? undefined : TweetUnionFromJSON(json['result']),
    };
}

export function ItemResultToJSON(value?: ItemResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '__typename': TypeNameToJSON(value.typename),
        'result': TweetUnionToJSON(value.result),
    };
}

