/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ListTweetsTimelineData } from './ListTweetsTimelineData';
import {
    ListTweetsTimelineDataFromJSON,
    ListTweetsTimelineDataFromJSONTyped,
    ListTweetsTimelineDataToJSON,
} from './ListTweetsTimelineData';

/**
 * 
 * @export
 * @interface ListLatestTweetsTimelineResponse
 */
export interface ListLatestTweetsTimelineResponse {
    /**
     * 
     * @type {ListTweetsTimelineData}
     * @memberof ListLatestTweetsTimelineResponse
     */
    data: ListTweetsTimelineData;
}

/**
 * Check if a given object implements the ListLatestTweetsTimelineResponse interface.
 */
export function instanceOfListLatestTweetsTimelineResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function ListLatestTweetsTimelineResponseFromJSON(json: any): ListLatestTweetsTimelineResponse {
    return ListLatestTweetsTimelineResponseFromJSONTyped(json, false);
}

export function ListLatestTweetsTimelineResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListLatestTweetsTimelineResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ListTweetsTimelineDataFromJSON(json['data']),
    };
}

export function ListLatestTweetsTimelineResponseToJSON(value?: ListLatestTweetsTimelineResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ListTweetsTimelineDataToJSON(value.data),
    };
}

