/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GrokImageAnnotation } from './GrokImageAnnotation';
import {
    GrokImageAnnotationFromJSON,
    GrokImageAnnotationFromJSONTyped,
    GrokImageAnnotationToJSON,
    GrokImageAnnotationToJSONTyped,
} from './GrokImageAnnotation';

/**
 * 
 * @export
 * @interface MediaResult
 */
export interface MediaResult {
    /**
     * 
     * @type {GrokImageAnnotation}
     * @memberof MediaResult
     */
    grokImageAnnotation?: GrokImageAnnotation;
    /**
     * 
     * @type {string}
     * @memberof MediaResult
     */
    mediaKey: string;
}

/**
 * Check if a given object implements the MediaResult interface.
 */
export function instanceOfMediaResult(value: object): value is MediaResult {
    if (!('mediaKey' in value) || value['mediaKey'] === undefined) return false;
    return true;
}

export function MediaResultFromJSON(json: any): MediaResult {
    return MediaResultFromJSONTyped(json, false);
}

export function MediaResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaResult {
    if (json == null) {
        return json;
    }
    return {
        
        'grokImageAnnotation': json['grok_image_annotation'] == null ? undefined : GrokImageAnnotationFromJSON(json['grok_image_annotation']),
        'mediaKey': json['media_key'],
    };
}

export function MediaResultToJSON(json: any): MediaResult {
    return MediaResultToJSONTyped(json, false);
}

export function MediaResultToJSONTyped(value?: MediaResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'grok_image_annotation': GrokImageAnnotationToJSON(value['grokImageAnnotation']),
        'media_key': value['mediaKey'],
    };
}

