/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MediaVisibilityResultsBlurredImageInterstitial } from './MediaVisibilityResultsBlurredImageInterstitial';
import {
    MediaVisibilityResultsBlurredImageInterstitialFromJSON,
    MediaVisibilityResultsBlurredImageInterstitialFromJSONTyped,
    MediaVisibilityResultsBlurredImageInterstitialToJSON,
} from './MediaVisibilityResultsBlurredImageInterstitial';

/**
 * 
 * @export
 * @interface MediaVisibilityResults
 */
export interface MediaVisibilityResults {
    /**
     * 
     * @type {MediaVisibilityResultsBlurredImageInterstitial}
     * @memberof MediaVisibilityResults
     */
    blurredImageInterstitial: MediaVisibilityResultsBlurredImageInterstitial;
}

/**
 * Check if a given object implements the MediaVisibilityResults interface.
 */
export function instanceOfMediaVisibilityResults(value: object): boolean {
    if (!('blurredImageInterstitial' in value)) return false;
    return true;
}

export function MediaVisibilityResultsFromJSON(json: any): MediaVisibilityResults {
    return MediaVisibilityResultsFromJSONTyped(json, false);
}

export function MediaVisibilityResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaVisibilityResults {
    if (json == null) {
        return json;
    }
    return {
        
        'blurredImageInterstitial': MediaVisibilityResultsBlurredImageInterstitialFromJSON(json['blurred_image_interstitial']),
    };
}

export function MediaVisibilityResultsToJSON(value?: MediaVisibilityResults | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'blurred_image_interstitial': MediaVisibilityResultsBlurredImageInterstitialToJSON(value['blurredImageInterstitial']),
    };
}

