/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MediaStats
 */
export interface MediaStats {
    /**
     * 
     * @type {number}
     * @memberof MediaStats
     */
    viewCount: number;
}

/**
 * Check if a given object implements the MediaStats interface.
 */
export function instanceOfMediaStats(value: object): value is MediaStats {
    if (!('viewCount' in value) || value['viewCount'] === undefined) return false;
    return true;
}

export function MediaStatsFromJSON(json: any): MediaStats {
    return MediaStatsFromJSONTyped(json, false);
}

export function MediaStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaStats {
    if (json == null) {
        return json;
    }
    return {
        
        'viewCount': json['viewCount'],
    };
}

export function MediaStatsToJSON(json: any): MediaStats {
    return MediaStatsToJSONTyped(json, false);
}

export function MediaStatsToJSONTyped(value?: MediaStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'viewCount': value['viewCount'],
    };
}

