/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MediaVideoInfoVariant
 */
export interface MediaVideoInfoVariant {
    /**
     * 
     * @type {number}
     * @memberof MediaVideoInfoVariant
     */
    bitrate?: number;
    /**
     * 
     * @type {string}
     * @memberof MediaVideoInfoVariant
     */
    contentType: string;
    /**
     * 
     * @type {string}
     * @memberof MediaVideoInfoVariant
     */
    url: string;
}

/**
 * Check if a given object implements the MediaVideoInfoVariant interface.
 */
export function instanceOfMediaVideoInfoVariant(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "contentType" in value;
    isInstance = isInstance && "url" in value;

    return isInstance;
}

export function MediaVideoInfoVariantFromJSON(json: any): MediaVideoInfoVariant {
    return MediaVideoInfoVariantFromJSONTyped(json, false);
}

export function MediaVideoInfoVariantFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaVideoInfoVariant {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bitrate': !exists(json, 'bitrate') ? undefined : json['bitrate'],
        'contentType': json['content_type'],
        'url': json['url'],
    };
}

export function MediaVideoInfoVariantToJSON(value?: MediaVideoInfoVariant | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bitrate': value.bitrate,
        'content_type': value.contentType,
        'url': value.url,
    };
}

