/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MediaSize } from './MediaSize';
import {
    MediaSizeFromJSON,
    MediaSizeFromJSONTyped,
    MediaSizeToJSON,
} from './MediaSize';

/**
 * 
 * @export
 * @interface MediaSizes
 */
export interface MediaSizes {
    /**
     * 
     * @type {MediaSize}
     * @memberof MediaSizes
     */
    large: MediaSize;
    /**
     * 
     * @type {MediaSize}
     * @memberof MediaSizes
     */
    medium: MediaSize;
    /**
     * 
     * @type {MediaSize}
     * @memberof MediaSizes
     */
    small: MediaSize;
    /**
     * 
     * @type {MediaSize}
     * @memberof MediaSizes
     */
    thumb: MediaSize;
}

/**
 * Check if a given object implements the MediaSizes interface.
 */
export function instanceOfMediaSizes(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "large" in value;
    isInstance = isInstance && "medium" in value;
    isInstance = isInstance && "small" in value;
    isInstance = isInstance && "thumb" in value;

    return isInstance;
}

export function MediaSizesFromJSON(json: any): MediaSizes {
    return MediaSizesFromJSONTyped(json, false);
}

export function MediaSizesFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaSizes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'large': MediaSizeFromJSON(json['large']),
        'medium': MediaSizeFromJSON(json['medium']),
        'small': MediaSizeFromJSON(json['small']),
        'thumb': MediaSizeFromJSON(json['thumb']),
    };
}

export function MediaSizesToJSON(value?: MediaSizes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'large': MediaSizeToJSON(value.large),
        'medium': MediaSizeToJSON(value.medium),
        'small': MediaSizeToJSON(value.small),
        'thumb': MediaSizeToJSON(value.thumb),
    };
}

