/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ModuleEntry } from './ModuleEntry';
import {
    ModuleEntryFromJSON,
    ModuleEntryFromJSONTyped,
    ModuleEntryToJSON,
} from './ModuleEntry';

/**
 * 
 * @export
 * @interface ModuleItem
 */
export interface ModuleItem {
    /**
     * 
     * @type {string}
     * @memberof ModuleItem
     */
    entryId: string;
    /**
     * 
     * @type {ModuleEntry}
     * @memberof ModuleItem
     */
    item: ModuleEntry;
}

/**
 * Check if a given object implements the ModuleItem interface.
 */
export function instanceOfModuleItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "entryId" in value;
    isInstance = isInstance && "item" in value;

    return isInstance;
}

export function ModuleItemFromJSON(json: any): ModuleItem {
    return ModuleItemFromJSONTyped(json, false);
}

export function ModuleItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModuleItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'entryId': json['entryId'],
        'item': ModuleEntryFromJSON(json['item']),
    };
}

export function ModuleItemToJSON(value?: ModuleItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'entryId': value.entryId,
        'item': ModuleEntryToJSON(value.item),
    };
}

