/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotificationsUserResults } from './NotificationsUserResults';
import {
    NotificationsUserResultsFromJSON,
    NotificationsUserResultsFromJSONTyped,
    NotificationsUserResultsToJSON,
    NotificationsUserResultsToJSONTyped,
} from './NotificationsUserResults';

/**
 * 
 * @export
 * @interface NotificationsViewerV2
 */
export interface NotificationsViewerV2 {
    /**
     * 
     * @type {NotificationsUserResults}
     * @memberof NotificationsViewerV2
     */
    userResults: NotificationsUserResults;
}

/**
 * Check if a given object implements the NotificationsViewerV2 interface.
 */
export function instanceOfNotificationsViewerV2(value: object): value is NotificationsViewerV2 {
    if (!('userResults' in value) || value['userResults'] === undefined) return false;
    return true;
}

export function NotificationsViewerV2FromJSON(json: any): NotificationsViewerV2 {
    return NotificationsViewerV2FromJSONTyped(json, false);
}

export function NotificationsViewerV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationsViewerV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'userResults': NotificationsUserResultsFromJSON(json['user_results']),
    };
}

export function NotificationsViewerV2ToJSON(json: any): NotificationsViewerV2 {
    return NotificationsViewerV2ToJSONTyped(json, false);
}

export function NotificationsViewerV2ToJSONTyped(value?: NotificationsViewerV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_results': NotificationsUserResultsToJSON(value['userResults']),
    };
}

