/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypeName } from './TypeName';
import {
    TypeNameFromJSON,
    TypeNameFromJSONTyped,
    TypeNameToJSON,
    TypeNameToJSONTyped,
} from './TypeName';

/**
 * 
 * @export
 * @interface NotificationTemplate
 */
export interface NotificationTemplate {
    /**
     * 
     * @type {TypeName}
     * @memberof NotificationTemplate
     */
    typename?: TypeName;
    /**
     * 
     * @type {Array<object>}
     * @memberof NotificationTemplate
     */
    fromUsers?: Array<object>;
    /**
     * 
     * @type {Array<object>}
     * @memberof NotificationTemplate
     */
    targetObjects?: Array<object>;
}



/**
 * Check if a given object implements the NotificationTemplate interface.
 */
export function instanceOfNotificationTemplate(value: object): value is NotificationTemplate {
    return true;
}

export function NotificationTemplateFromJSON(json: any): NotificationTemplate {
    return NotificationTemplateFromJSONTyped(json, false);
}

export function NotificationTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationTemplate {
    if (json == null) {
        return json;
    }
    return {
        
        'typename': json['__typename'] == null ? undefined : TypeNameFromJSON(json['__typename']),
        'fromUsers': json['from_users'] == null ? undefined : json['from_users'],
        'targetObjects': json['target_objects'] == null ? undefined : json['target_objects'],
    };
}

export function NotificationTemplateToJSON(json: any): NotificationTemplate {
    return NotificationTemplateToJSONTyped(json, false);
}

export function NotificationTemplateToJSONTyped(value?: NotificationTemplate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '__typename': TypeNameToJSON(value['typename']),
        'from_users': value['fromUsers'],
        'target_objects': value['targetObjects'],
    };
}

