/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostCreateTweetRequestVariablesReply
 */
export interface PostCreateTweetRequestVariablesReply {
    /**
     * 
     * @type {Array<object>}
     * @memberof PostCreateTweetRequestVariablesReply
     */
    excludeReplyUserIds: Array<object>;
    /**
     * 
     * @type {string}
     * @memberof PostCreateTweetRequestVariablesReply
     */
    inReplyToTweetId: string;
}

/**
 * Check if a given object implements the PostCreateTweetRequestVariablesReply interface.
 */
export function instanceOfPostCreateTweetRequestVariablesReply(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "excludeReplyUserIds" in value;
    isInstance = isInstance && "inReplyToTweetId" in value;

    return isInstance;
}

export function PostCreateTweetRequestVariablesReplyFromJSON(json: any): PostCreateTweetRequestVariablesReply {
    return PostCreateTweetRequestVariablesReplyFromJSONTyped(json, false);
}

export function PostCreateTweetRequestVariablesReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostCreateTweetRequestVariablesReply {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'excludeReplyUserIds': json['exclude_reply_user_ids'],
        'inReplyToTweetId': json['in_reply_to_tweet_id'],
    };
}

export function PostCreateTweetRequestVariablesReplyToJSON(value?: PostCreateTweetRequestVariablesReply | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'exclude_reply_user_ids': value.excludeReplyUserIds,
        'in_reply_to_tweet_id': value.inReplyToTweetId,
    };
}

