/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PostCreateTweetRequestVariablesMediaMediaEntitiesInner } from './PostCreateTweetRequestVariablesMediaMediaEntitiesInner';
import {
    PostCreateTweetRequestVariablesMediaMediaEntitiesInnerFromJSON,
    PostCreateTweetRequestVariablesMediaMediaEntitiesInnerFromJSONTyped,
    PostCreateTweetRequestVariablesMediaMediaEntitiesInnerToJSON,
} from './PostCreateTweetRequestVariablesMediaMediaEntitiesInner';

/**
 * 
 * @export
 * @interface PostCreateTweetRequestVariablesMedia
 */
export interface PostCreateTweetRequestVariablesMedia {
    /**
     * 
     * @type {Array<PostCreateTweetRequestVariablesMediaMediaEntitiesInner>}
     * @memberof PostCreateTweetRequestVariablesMedia
     */
    mediaEntities: Array<PostCreateTweetRequestVariablesMediaMediaEntitiesInner>;
    /**
     * 
     * @type {boolean}
     * @memberof PostCreateTweetRequestVariablesMedia
     */
    possiblySensitive: boolean;
}

/**
 * Check if a given object implements the PostCreateTweetRequestVariablesMedia interface.
 */
export function instanceOfPostCreateTweetRequestVariablesMedia(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "mediaEntities" in value;
    isInstance = isInstance && "possiblySensitive" in value;

    return isInstance;
}

export function PostCreateTweetRequestVariablesMediaFromJSON(json: any): PostCreateTweetRequestVariablesMedia {
    return PostCreateTweetRequestVariablesMediaFromJSONTyped(json, false);
}

export function PostCreateTweetRequestVariablesMediaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostCreateTweetRequestVariablesMedia {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mediaEntities': ((json['media_entities'] as Array<any>).map(PostCreateTweetRequestVariablesMediaMediaEntitiesInnerFromJSON)),
        'possiblySensitive': json['possibly_sensitive'],
    };
}

export function PostCreateTweetRequestVariablesMediaToJSON(value?: PostCreateTweetRequestVariablesMedia | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'media_entities': ((value.mediaEntities as Array<any>).map(PostCreateTweetRequestVariablesMediaMediaEntitiesInnerToJSON)),
        'possibly_sensitive': value.possiblySensitive,
    };
}

