/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostCreateRetweetRequestVariables } from './PostCreateRetweetRequestVariables';
import {
    PostCreateRetweetRequestVariablesFromJSON,
    PostCreateRetweetRequestVariablesFromJSONTyped,
    PostCreateRetweetRequestVariablesToJSON,
} from './PostCreateRetweetRequestVariables';

/**
 * 
 * @export
 * @interface PostUnfavoriteTweetRequest
 */
export interface PostUnfavoriteTweetRequest {
    /**
     * 
     * @type {string}
     * @memberof PostUnfavoriteTweetRequest
     */
    queryId: string;
    /**
     * 
     * @type {PostCreateRetweetRequestVariables}
     * @memberof PostUnfavoriteTweetRequest
     */
    variables: PostCreateRetweetRequestVariables;
}

/**
 * Check if a given object implements the PostUnfavoriteTweetRequest interface.
 */
export function instanceOfPostUnfavoriteTweetRequest(value: object): value is PostUnfavoriteTweetRequest {
    if (!('queryId' in value) || value['queryId'] === undefined) return false;
    if (!('variables' in value) || value['variables'] === undefined) return false;
    return true;
}

export function PostUnfavoriteTweetRequestFromJSON(json: any): PostUnfavoriteTweetRequest {
    return PostUnfavoriteTweetRequestFromJSONTyped(json, false);
}

export function PostUnfavoriteTweetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostUnfavoriteTweetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'queryId': json['queryId'],
        'variables': PostCreateRetweetRequestVariablesFromJSON(json['variables']),
    };
}

export function PostUnfavoriteTweetRequestToJSON(value?: PostUnfavoriteTweetRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'queryId': value['queryId'],
        'variables': PostCreateRetweetRequestVariablesToJSON(value['variables']),
    };
}

