/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostCreateTweetRequestFeatures
 */
export interface PostCreateTweetRequestFeatures {
    /**
     * 
     * @type {boolean}
     * @memberof PostCreateTweetRequestFeatures
     */
    articlesPreviewEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PostCreateTweetRequestFeatures
     */
    c9sTweetAnatomyModeratorBadgeEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PostCreateTweetRequestFeatures
     */
    communitiesWebEnableTweetCommunityResultsFetch: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PostCreateTweetRequestFeatures
     */
    creatorSubscriptionsQuoteTweetPreviewEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PostCreateTweetRequestFeatures
     */
    freedomOfSpeechNotReachFetchEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PostCreateTweetRequestFeatures
     */
    graphqlIsTranslatableRwebTweetIsTranslatableEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PostCreateTweetRequestFeatures
     */
    longformNotetweetsConsumptionEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PostCreateTweetRequestFeatures
     */
    longformNotetweetsInlineMediaEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PostCreateTweetRequestFeatures
     */
    longformNotetweetsRichTextReadEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PostCreateTweetRequestFeatures
     */
    responsiveWebEditTweetApiEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PostCreateTweetRequestFeatures
     */
    responsiveWebEnhanceCardsEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PostCreateTweetRequestFeatures
     */
    responsiveWebGraphqlExcludeDirectiveEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PostCreateTweetRequestFeatures
     */
    responsiveWebGraphqlSkipUserProfileImageExtensionsEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PostCreateTweetRequestFeatures
     */
    responsiveWebGraphqlTimelineNavigationEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PostCreateTweetRequestFeatures
     */
    responsiveWebTwitterArticleTweetConsumptionEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PostCreateTweetRequestFeatures
     */
    rwebTipjarConsumptionEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PostCreateTweetRequestFeatures
     */
    rwebVideoTimestampsEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PostCreateTweetRequestFeatures
     */
    standardizedNudgesMisinfo: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PostCreateTweetRequestFeatures
     */
    tweetAwardsWebTippingEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PostCreateTweetRequestFeatures
     */
    tweetWithVisibilityResultsPreferGqlLimitedActionsPolicyEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PostCreateTweetRequestFeatures
     */
    verifiedPhoneLabelEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PostCreateTweetRequestFeatures
     */
    viewCountsEverywhereApiEnabled: boolean;
}

/**
 * Check if a given object implements the PostCreateTweetRequestFeatures interface.
 */
export function instanceOfPostCreateTweetRequestFeatures(value: object): value is PostCreateTweetRequestFeatures {
    if (!('articlesPreviewEnabled' in value) || value['articlesPreviewEnabled'] === undefined) return false;
    if (!('c9sTweetAnatomyModeratorBadgeEnabled' in value) || value['c9sTweetAnatomyModeratorBadgeEnabled'] === undefined) return false;
    if (!('communitiesWebEnableTweetCommunityResultsFetch' in value) || value['communitiesWebEnableTweetCommunityResultsFetch'] === undefined) return false;
    if (!('creatorSubscriptionsQuoteTweetPreviewEnabled' in value) || value['creatorSubscriptionsQuoteTweetPreviewEnabled'] === undefined) return false;
    if (!('freedomOfSpeechNotReachFetchEnabled' in value) || value['freedomOfSpeechNotReachFetchEnabled'] === undefined) return false;
    if (!('graphqlIsTranslatableRwebTweetIsTranslatableEnabled' in value) || value['graphqlIsTranslatableRwebTweetIsTranslatableEnabled'] === undefined) return false;
    if (!('longformNotetweetsConsumptionEnabled' in value) || value['longformNotetweetsConsumptionEnabled'] === undefined) return false;
    if (!('longformNotetweetsInlineMediaEnabled' in value) || value['longformNotetweetsInlineMediaEnabled'] === undefined) return false;
    if (!('longformNotetweetsRichTextReadEnabled' in value) || value['longformNotetweetsRichTextReadEnabled'] === undefined) return false;
    if (!('responsiveWebEditTweetApiEnabled' in value) || value['responsiveWebEditTweetApiEnabled'] === undefined) return false;
    if (!('responsiveWebEnhanceCardsEnabled' in value) || value['responsiveWebEnhanceCardsEnabled'] === undefined) return false;
    if (!('responsiveWebGraphqlExcludeDirectiveEnabled' in value) || value['responsiveWebGraphqlExcludeDirectiveEnabled'] === undefined) return false;
    if (!('responsiveWebGraphqlSkipUserProfileImageExtensionsEnabled' in value) || value['responsiveWebGraphqlSkipUserProfileImageExtensionsEnabled'] === undefined) return false;
    if (!('responsiveWebGraphqlTimelineNavigationEnabled' in value) || value['responsiveWebGraphqlTimelineNavigationEnabled'] === undefined) return false;
    if (!('responsiveWebTwitterArticleTweetConsumptionEnabled' in value) || value['responsiveWebTwitterArticleTweetConsumptionEnabled'] === undefined) return false;
    if (!('rwebTipjarConsumptionEnabled' in value) || value['rwebTipjarConsumptionEnabled'] === undefined) return false;
    if (!('rwebVideoTimestampsEnabled' in value) || value['rwebVideoTimestampsEnabled'] === undefined) return false;
    if (!('standardizedNudgesMisinfo' in value) || value['standardizedNudgesMisinfo'] === undefined) return false;
    if (!('tweetAwardsWebTippingEnabled' in value) || value['tweetAwardsWebTippingEnabled'] === undefined) return false;
    if (!('tweetWithVisibilityResultsPreferGqlLimitedActionsPolicyEnabled' in value) || value['tweetWithVisibilityResultsPreferGqlLimitedActionsPolicyEnabled'] === undefined) return false;
    if (!('verifiedPhoneLabelEnabled' in value) || value['verifiedPhoneLabelEnabled'] === undefined) return false;
    if (!('viewCountsEverywhereApiEnabled' in value) || value['viewCountsEverywhereApiEnabled'] === undefined) return false;
    return true;
}

export function PostCreateTweetRequestFeaturesFromJSON(json: any): PostCreateTweetRequestFeatures {
    return PostCreateTweetRequestFeaturesFromJSONTyped(json, false);
}

export function PostCreateTweetRequestFeaturesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostCreateTweetRequestFeatures {
    if (json == null) {
        return json;
    }
    return {
        
        'articlesPreviewEnabled': json['articles_preview_enabled'],
        'c9sTweetAnatomyModeratorBadgeEnabled': json['c9s_tweet_anatomy_moderator_badge_enabled'],
        'communitiesWebEnableTweetCommunityResultsFetch': json['communities_web_enable_tweet_community_results_fetch'],
        'creatorSubscriptionsQuoteTweetPreviewEnabled': json['creator_subscriptions_quote_tweet_preview_enabled'],
        'freedomOfSpeechNotReachFetchEnabled': json['freedom_of_speech_not_reach_fetch_enabled'],
        'graphqlIsTranslatableRwebTweetIsTranslatableEnabled': json['graphql_is_translatable_rweb_tweet_is_translatable_enabled'],
        'longformNotetweetsConsumptionEnabled': json['longform_notetweets_consumption_enabled'],
        'longformNotetweetsInlineMediaEnabled': json['longform_notetweets_inline_media_enabled'],
        'longformNotetweetsRichTextReadEnabled': json['longform_notetweets_rich_text_read_enabled'],
        'responsiveWebEditTweetApiEnabled': json['responsive_web_edit_tweet_api_enabled'],
        'responsiveWebEnhanceCardsEnabled': json['responsive_web_enhance_cards_enabled'],
        'responsiveWebGraphqlExcludeDirectiveEnabled': json['responsive_web_graphql_exclude_directive_enabled'],
        'responsiveWebGraphqlSkipUserProfileImageExtensionsEnabled': json['responsive_web_graphql_skip_user_profile_image_extensions_enabled'],
        'responsiveWebGraphqlTimelineNavigationEnabled': json['responsive_web_graphql_timeline_navigation_enabled'],
        'responsiveWebTwitterArticleTweetConsumptionEnabled': json['responsive_web_twitter_article_tweet_consumption_enabled'],
        'rwebTipjarConsumptionEnabled': json['rweb_tipjar_consumption_enabled'],
        'rwebVideoTimestampsEnabled': json['rweb_video_timestamps_enabled'],
        'standardizedNudgesMisinfo': json['standardized_nudges_misinfo'],
        'tweetAwardsWebTippingEnabled': json['tweet_awards_web_tipping_enabled'],
        'tweetWithVisibilityResultsPreferGqlLimitedActionsPolicyEnabled': json['tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled'],
        'verifiedPhoneLabelEnabled': json['verified_phone_label_enabled'],
        'viewCountsEverywhereApiEnabled': json['view_counts_everywhere_api_enabled'],
    };
}

export function PostCreateTweetRequestFeaturesToJSON(json: any): PostCreateTweetRequestFeatures {
    return PostCreateTweetRequestFeaturesToJSONTyped(json, false);
}

export function PostCreateTweetRequestFeaturesToJSONTyped(value?: PostCreateTweetRequestFeatures | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'articles_preview_enabled': value['articlesPreviewEnabled'],
        'c9s_tweet_anatomy_moderator_badge_enabled': value['c9sTweetAnatomyModeratorBadgeEnabled'],
        'communities_web_enable_tweet_community_results_fetch': value['communitiesWebEnableTweetCommunityResultsFetch'],
        'creator_subscriptions_quote_tweet_preview_enabled': value['creatorSubscriptionsQuoteTweetPreviewEnabled'],
        'freedom_of_speech_not_reach_fetch_enabled': value['freedomOfSpeechNotReachFetchEnabled'],
        'graphql_is_translatable_rweb_tweet_is_translatable_enabled': value['graphqlIsTranslatableRwebTweetIsTranslatableEnabled'],
        'longform_notetweets_consumption_enabled': value['longformNotetweetsConsumptionEnabled'],
        'longform_notetweets_inline_media_enabled': value['longformNotetweetsInlineMediaEnabled'],
        'longform_notetweets_rich_text_read_enabled': value['longformNotetweetsRichTextReadEnabled'],
        'responsive_web_edit_tweet_api_enabled': value['responsiveWebEditTweetApiEnabled'],
        'responsive_web_enhance_cards_enabled': value['responsiveWebEnhanceCardsEnabled'],
        'responsive_web_graphql_exclude_directive_enabled': value['responsiveWebGraphqlExcludeDirectiveEnabled'],
        'responsive_web_graphql_skip_user_profile_image_extensions_enabled': value['responsiveWebGraphqlSkipUserProfileImageExtensionsEnabled'],
        'responsive_web_graphql_timeline_navigation_enabled': value['responsiveWebGraphqlTimelineNavigationEnabled'],
        'responsive_web_twitter_article_tweet_consumption_enabled': value['responsiveWebTwitterArticleTweetConsumptionEnabled'],
        'rweb_tipjar_consumption_enabled': value['rwebTipjarConsumptionEnabled'],
        'rweb_video_timestamps_enabled': value['rwebVideoTimestampsEnabled'],
        'standardized_nudges_misinfo': value['standardizedNudgesMisinfo'],
        'tweet_awards_web_tipping_enabled': value['tweetAwardsWebTippingEnabled'],
        'tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled': value['tweetWithVisibilityResultsPreferGqlLimitedActionsPolicyEnabled'],
        'verified_phone_label_enabled': value['verifiedPhoneLabelEnabled'],
        'view_counts_everywhere_api_enabled': value['viewCountsEverywhereApiEnabled'],
    };
}

