/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypeName } from './TypeName';
import {
    TypeNameFromJSON,
    TypeNameFromJSONTyped,
    TypeNameToJSON,
    TypeNameToJSONTyped,
} from './TypeName';
import type { TimelineResult } from './TimelineResult';
import {
    TimelineResultFromJSON,
    TimelineResultFromJSONTyped,
    TimelineResultToJSON,
    TimelineResultToJSONTyped,
} from './TimelineResult';

/**
 * 
 * @export
 * @interface RankedCommunityResult
 */
export interface RankedCommunityResult {
    /**
     * 
     * @type {TypeName}
     * @memberof RankedCommunityResult
     */
    typename: TypeName;
    /**
     * 
     * @type {TimelineResult}
     * @memberof RankedCommunityResult
     */
    rankedCommunityTimeline: TimelineResult;
}



/**
 * Check if a given object implements the RankedCommunityResult interface.
 */
export function instanceOfRankedCommunityResult(value: object): value is RankedCommunityResult {
    if (!('typename' in value) || value['typename'] === undefined) return false;
    if (!('rankedCommunityTimeline' in value) || value['rankedCommunityTimeline'] === undefined) return false;
    return true;
}

export function RankedCommunityResultFromJSON(json: any): RankedCommunityResult {
    return RankedCommunityResultFromJSONTyped(json, false);
}

export function RankedCommunityResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): RankedCommunityResult {
    if (json == null) {
        return json;
    }
    return {
        
        'typename': TypeNameFromJSON(json['__typename']),
        'rankedCommunityTimeline': TimelineResultFromJSON(json['ranked_community_timeline']),
    };
}

export function RankedCommunityResultToJSON(json: any): RankedCommunityResult {
    return RankedCommunityResultToJSONTyped(json, false);
}

export function RankedCommunityResultToJSONTyped(value?: RankedCommunityResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '__typename': TypeNameToJSON(value['typename']),
        'ranked_community_timeline': TimelineResultToJSON(value['rankedCommunityTimeline']),
    };
}

