/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RetweetLegacy
 */
export interface RetweetLegacy {
    /**
     * 
     * @type {string}
     * @memberof RetweetLegacy
     */
    fullText: string;
}

/**
 * Check if a given object implements the RetweetLegacy interface.
 */
export function instanceOfRetweetLegacy(value: object): value is RetweetLegacy {
    if (!('fullText' in value) || value['fullText'] === undefined) return false;
    return true;
}

export function RetweetLegacyFromJSON(json: any): RetweetLegacy {
    return RetweetLegacyFromJSONTyped(json, false);
}

export function RetweetLegacyFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetweetLegacy {
    if (json == null) {
        return json;
    }
    return {
        
        'fullText': json['full_text'],
    };
}

export function RetweetLegacyToJSON(value?: RetweetLegacy | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'full_text': value['fullText'],
    };
}

