/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchTimeline } from './SearchTimeline';
import {
    SearchTimelineFromJSON,
    SearchTimelineFromJSONTyped,
    SearchTimelineToJSON,
} from './SearchTimeline';

/**
 * 
 * @export
 * @interface SearchByRawQuery
 */
export interface SearchByRawQuery {
    /**
     * 
     * @type {SearchTimeline}
     * @memberof SearchByRawQuery
     */
    searchTimeline: SearchTimeline;
}

/**
 * Check if a given object implements the SearchByRawQuery interface.
 */
export function instanceOfSearchByRawQuery(value: object): value is SearchByRawQuery {
    if (!('searchTimeline' in value) || value['searchTimeline'] === undefined) return false;
    return true;
}

export function SearchByRawQueryFromJSON(json: any): SearchByRawQuery {
    return SearchByRawQueryFromJSONTyped(json, false);
}

export function SearchByRawQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchByRawQuery {
    if (json == null) {
        return json;
    }
    return {
        
        'searchTimeline': SearchTimelineFromJSON(json['search_timeline']),
    };
}

export function SearchByRawQueryToJSON(value?: SearchByRawQuery | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'search_timeline': SearchTimelineToJSON(value['searchTimeline']),
    };
}

