/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SocialContextUnionType = {
    TimelineGeneralContext: 'TimelineGeneralContext',
    TimelineTopicContext: 'TimelineTopicContext'
} as const;
export type SocialContextUnionType = typeof SocialContextUnionType[keyof typeof SocialContextUnionType];


export function instanceOfSocialContextUnionType(value: any): boolean {
    for (const key in SocialContextUnionType) {
        if (Object.prototype.hasOwnProperty.call(SocialContextUnionType, key)) {
            if (SocialContextUnionType[key as keyof typeof SocialContextUnionType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SocialContextUnionTypeFromJSON(json: any): SocialContextUnionType {
    return SocialContextUnionTypeFromJSONTyped(json, false);
}

export function SocialContextUnionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SocialContextUnionType {
    return json as SocialContextUnionType;
}

export function SocialContextUnionTypeToJSON(value?: SocialContextUnionType | null): any {
    return value as any;
}

export function SocialContextUnionTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): SocialContextUnionType {
    return value as SocialContextUnionType;
}

