/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SuperFollowsReplyUserResultLegacy } from './SuperFollowsReplyUserResultLegacy';
import {
    SuperFollowsReplyUserResultLegacyFromJSON,
    SuperFollowsReplyUserResultLegacyFromJSONTyped,
    SuperFollowsReplyUserResultLegacyToJSON,
} from './SuperFollowsReplyUserResultLegacy';
import type { TypeName } from './TypeName';
import {
    TypeNameFromJSON,
    TypeNameFromJSONTyped,
    TypeNameToJSON,
} from './TypeName';

/**
 * 
 * @export
 * @interface SuperFollowsReplyUserResultData
 */
export interface SuperFollowsReplyUserResultData {
    /**
     * 
     * @type {TypeName}
     * @memberof SuperFollowsReplyUserResultData
     */
    typename: TypeName;
    /**
     * 
     * @type {SuperFollowsReplyUserResultLegacy}
     * @memberof SuperFollowsReplyUserResultData
     */
    legacy: SuperFollowsReplyUserResultLegacy;
}

/**
 * Check if a given object implements the SuperFollowsReplyUserResultData interface.
 */
export function instanceOfSuperFollowsReplyUserResultData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "typename" in value;
    isInstance = isInstance && "legacy" in value;

    return isInstance;
}

export function SuperFollowsReplyUserResultDataFromJSON(json: any): SuperFollowsReplyUserResultData {
    return SuperFollowsReplyUserResultDataFromJSONTyped(json, false);
}

export function SuperFollowsReplyUserResultDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuperFollowsReplyUserResultData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'typename': TypeNameFromJSON(json['__typename']),
        'legacy': SuperFollowsReplyUserResultLegacyFromJSON(json['legacy']),
    };
}

export function SuperFollowsReplyUserResultDataToJSON(value?: SuperFollowsReplyUserResultData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '__typename': TypeNameToJSON(value.typename),
        'legacy': SuperFollowsReplyUserResultLegacyToJSON(value.legacy),
    };
}

