/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TextEntityRef } from './TextEntityRef';
import {
    TextEntityRefFromJSON,
    TextEntityRefFromJSONTyped,
    TextEntityRefToJSON,
} from './TextEntityRef';

/**
 * 
 * @export
 * @interface TextEntity
 */
export interface TextEntity {
    /**
     * 
     * @type {number}
     * @memberof TextEntity
     */
    fromIndex: number;
    /**
     * 
     * @type {TextEntityRef}
     * @memberof TextEntity
     */
    ref: TextEntityRef;
    /**
     * 
     * @type {number}
     * @memberof TextEntity
     */
    toIndex: number;
}

/**
 * Check if a given object implements the TextEntity interface.
 */
export function instanceOfTextEntity(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "fromIndex" in value;
    isInstance = isInstance && "ref" in value;
    isInstance = isInstance && "toIndex" in value;

    return isInstance;
}

export function TextEntityFromJSON(json: any): TextEntity {
    return TextEntityFromJSONTyped(json, false);
}

export function TextEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): TextEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fromIndex': json['fromIndex'],
        'ref': TextEntityRefFromJSON(json['ref']),
        'toIndex': json['toIndex'],
    };
}

export function TextEntityToJSON(value?: TextEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fromIndex': value.fromIndex,
        'ref': TextEntityRefToJSON(value.ref),
        'toIndex': value.toIndex,
    };
}

