/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Timestamp
 */
export interface Timestamp {
    /**
     * 
     * @type {Array<number>}
     * @memberof Timestamp
     */
    indices: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof Timestamp
     */
    seconds: number;
    /**
     * 
     * @type {string}
     * @memberof Timestamp
     */
    text: string;
}

/**
 * Check if a given object implements the Timestamp interface.
 */
export function instanceOfTimestamp(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "indices" in value;
    isInstance = isInstance && "seconds" in value;
    isInstance = isInstance && "text" in value;

    return isInstance;
}

export function TimestampFromJSON(json: any): Timestamp {
    return TimestampFromJSONTyped(json, false);
}

export function TimestampFromJSONTyped(json: any, ignoreDiscriminator: boolean): Timestamp {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'indices': json['indices'],
        'seconds': json['seconds'],
        'text': json['text'],
    };
}

export function TimestampToJSON(value?: Timestamp | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'indices': value.indices,
        'seconds': value.seconds,
        'text': value.text,
    };
}

