/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimelineCoverBehavior
 */
export interface TimelineCoverBehavior {
    /**
     * 
     * @type {string}
     * @memberof TimelineCoverBehavior
     */
    type: TimelineCoverBehaviorTypeEnum;
}


/**
 * @export
 */
export const TimelineCoverBehaviorTypeEnum = {
    TimelineCoverBehaviorDismiss: 'TimelineCoverBehaviorDismiss'
} as const;
export type TimelineCoverBehaviorTypeEnum = typeof TimelineCoverBehaviorTypeEnum[keyof typeof TimelineCoverBehaviorTypeEnum];


/**
 * Check if a given object implements the TimelineCoverBehavior interface.
 */
export function instanceOfTimelineCoverBehavior(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function TimelineCoverBehaviorFromJSON(json: any): TimelineCoverBehavior {
    return TimelineCoverBehaviorFromJSONTyped(json, false);
}

export function TimelineCoverBehaviorFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimelineCoverBehavior {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function TimelineCoverBehaviorToJSON(value?: TimelineCoverBehavior | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
    };
}

