/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ContentUnion } from './ContentUnion';
import {
    ContentUnionFromJSON,
    ContentUnionFromJSONTyped,
    ContentUnionToJSON,
} from './ContentUnion';

/**
 * 
 * @export
 * @interface TimelineAddEntry
 */
export interface TimelineAddEntry {
    /**
     * 
     * @type {ContentUnion}
     * @memberof TimelineAddEntry
     */
    content: ContentUnion;
    /**
     * 
     * @type {string}
     * @memberof TimelineAddEntry
     */
    entryId: string;
    /**
     * 
     * @type {string}
     * @memberof TimelineAddEntry
     */
    sortIndex: string;
}

/**
 * Check if a given object implements the TimelineAddEntry interface.
 */
export function instanceOfTimelineAddEntry(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "content" in value;
    isInstance = isInstance && "entryId" in value;
    isInstance = isInstance && "sortIndex" in value;

    return isInstance;
}

export function TimelineAddEntryFromJSON(json: any): TimelineAddEntry {
    return TimelineAddEntryFromJSONTyped(json, false);
}

export function TimelineAddEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimelineAddEntry {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'content': ContentUnionFromJSON(json['content']),
        'entryId': json['entryId'],
        'sortIndex': json['sortIndex'],
    };
}

export function TimelineAddEntryToJSON(value?: TimelineAddEntry | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'content': ContentUnionToJSON(value.content),
        'entryId': value.entryId,
        'sortIndex': value.sortIndex,
    };
}

