/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypeName } from './TypeName';
import {
    TypeNameFromJSON,
    TypeNameFromJSONTyped,
    TypeNameToJSON,
} from './TypeName';

/**
 * 
 * @export
 * @interface TimelinePrompt
 */
export interface TimelinePrompt {
    [key: string]: any | any;
    /**
     * 
     * @type {TypeName}
     * @memberof TimelinePrompt
     */
    typename?: TypeName;
}



/**
 * Check if a given object implements the TimelinePrompt interface.
 */
export function instanceOfTimelinePrompt(value: object): value is TimelinePrompt {
    return true;
}

export function TimelinePromptFromJSON(json: any): TimelinePrompt {
    return TimelinePromptFromJSONTyped(json, false);
}

export function TimelinePromptFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimelinePrompt {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'typename': json['__typename'] == null ? undefined : TypeNameFromJSON(json['__typename']),
    };
}

export function TimelinePromptToJSON(value?: TimelinePrompt | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        '__typename': TypeNameToJSON(value['typename']),
    };
}

