/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Tracing
 */
export interface Tracing {
    /**
     * 
     * @type {string}
     * @memberof Tracing
     */
    traceId: string;
}

/**
 * Check if a given object implements the Tracing interface.
 */
export function instanceOfTracing(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "traceId" in value;

    return isInstance;
}

export function TracingFromJSON(json: any): Tracing {
    return TracingFromJSONTyped(json, false);
}

export function TracingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tracing {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'traceId': json['trace_id'],
    };
}

export function TracingToJSON(value?: Tracing | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'trace_id': value.traceId,
    };
}

