/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TweetRetweetersResponseData } from './TweetRetweetersResponseData';
import {
    TweetRetweetersResponseDataFromJSON,
    TweetRetweetersResponseDataFromJSONTyped,
    TweetRetweetersResponseDataToJSON,
} from './TweetRetweetersResponseData';

/**
 * 
 * @export
 * @interface TweetRetweetersResponse
 */
export interface TweetRetweetersResponse {
    /**
     * 
     * @type {TweetRetweetersResponseData}
     * @memberof TweetRetweetersResponse
     */
    data: TweetRetweetersResponseData;
}

/**
 * Check if a given object implements the TweetRetweetersResponse interface.
 */
export function instanceOfTweetRetweetersResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function TweetRetweetersResponseFromJSON(json: any): TweetRetweetersResponse {
    return TweetRetweetersResponseFromJSONTyped(json, false);
}

export function TweetRetweetersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TweetRetweetersResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': TweetRetweetersResponseDataFromJSON(json['data']),
    };
}

export function TweetRetweetersResponseToJSON(value?: TweetRetweetersResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': TweetRetweetersResponseDataToJSON(value.data),
    };
}

