/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TweetCardLegacy } from './TweetCardLegacy';
import {
    TweetCardLegacyFromJSON,
    TweetCardLegacyFromJSONTyped,
    TweetCardLegacyToJSON,
} from './TweetCardLegacy';

/**
 * 
 * @export
 * @interface TweetCard
 */
export interface TweetCard {
    /**
     * 
     * @type {TweetCardLegacy}
     * @memberof TweetCard
     */
    legacy?: TweetCardLegacy;
    /**
     * 
     * @type {string}
     * @memberof TweetCard
     */
    restId?: string;
}

/**
 * Check if a given object implements the TweetCard interface.
 */
export function instanceOfTweetCard(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TweetCardFromJSON(json: any): TweetCard {
    return TweetCardFromJSONTyped(json, false);
}

export function TweetCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): TweetCard {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'legacy': !exists(json, 'legacy') ? undefined : TweetCardLegacyFromJSON(json['legacy']),
        'restId': !exists(json, 'rest_id') ? undefined : json['rest_id'],
    };
}

export function TweetCardToJSON(value?: TweetCard | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'legacy': TweetCardLegacyToJSON(value.legacy),
        'rest_id': value.restId,
    };
}

