/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TweetEditControlInitial } from './TweetEditControlInitial';
import {
    TweetEditControlInitialFromJSON,
    TweetEditControlInitialFromJSONTyped,
    TweetEditControlInitialToJSON,
    TweetEditControlInitialToJSONTyped,
} from './TweetEditControlInitial';

/**
 * 
 * @export
 * @interface TweetEditControl
 */
export interface TweetEditControl {
    /**
     * 
     * @type {TweetEditControlInitial}
     * @memberof TweetEditControl
     */
    editControlInitial?: TweetEditControlInitial;
    /**
     * 
     * @type {Array<string>}
     * @memberof TweetEditControl
     */
    editTweetIds?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof TweetEditControl
     */
    editableUntilMsecs?: string;
    /**
     * 
     * @type {string}
     * @memberof TweetEditControl
     */
    editsRemaining?: string;
    /**
     * 
     * @type {string}
     * @memberof TweetEditControl
     */
    initialTweetId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TweetEditControl
     */
    isEditEligible?: boolean;
}

/**
 * Check if a given object implements the TweetEditControl interface.
 */
export function instanceOfTweetEditControl(value: object): value is TweetEditControl {
    return true;
}

export function TweetEditControlFromJSON(json: any): TweetEditControl {
    return TweetEditControlFromJSONTyped(json, false);
}

export function TweetEditControlFromJSONTyped(json: any, ignoreDiscriminator: boolean): TweetEditControl {
    if (json == null) {
        return json;
    }
    return {
        
        'editControlInitial': json['edit_control_initial'] == null ? undefined : TweetEditControlInitialFromJSON(json['edit_control_initial']),
        'editTweetIds': json['edit_tweet_ids'] == null ? undefined : json['edit_tweet_ids'],
        'editableUntilMsecs': json['editable_until_msecs'] == null ? undefined : json['editable_until_msecs'],
        'editsRemaining': json['edits_remaining'] == null ? undefined : json['edits_remaining'],
        'initialTweetId': json['initial_tweet_id'] == null ? undefined : json['initial_tweet_id'],
        'isEditEligible': json['is_edit_eligible'] == null ? undefined : json['is_edit_eligible'],
    };
}

export function TweetEditControlToJSON(json: any): TweetEditControl {
    return TweetEditControlToJSONTyped(json, false);
}

export function TweetEditControlToJSONTyped(value?: TweetEditControl | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'edit_control_initial': TweetEditControlInitialToJSON(value['editControlInitial']),
        'edit_tweet_ids': value['editTweetIds'],
        'editable_until_msecs': value['editableUntilMsecs'],
        'edits_remaining': value['editsRemaining'],
        'initial_tweet_id': value['initialTweetId'],
        'is_edit_eligible': value['isEditEligible'],
    };
}

