/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Timeline } from './Timeline';
import {
    TimelineFromJSON,
    TimelineFromJSONTyped,
    TimelineToJSON,
} from './Timeline';

/**
 * 
 * @export
 * @interface TweetDetailResponseData
 */
export interface TweetDetailResponseData {
    /**
     * 
     * @type {Timeline}
     * @memberof TweetDetailResponseData
     */
    threadedConversationWithInjectionsV2: Timeline;
}

/**
 * Check if a given object implements the TweetDetailResponseData interface.
 */
export function instanceOfTweetDetailResponseData(value: object): value is TweetDetailResponseData {
    if (!('threadedConversationWithInjectionsV2' in value) || value['threadedConversationWithInjectionsV2'] === undefined) return false;
    return true;
}

export function TweetDetailResponseDataFromJSON(json: any): TweetDetailResponseData {
    return TweetDetailResponseDataFromJSONTyped(json, false);
}

export function TweetDetailResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TweetDetailResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'threadedConversationWithInjectionsV2': TimelineFromJSON(json['threaded_conversation_with_injections_v2']),
    };
}

export function TweetDetailResponseDataToJSON(value?: TweetDetailResponseData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'threaded_conversation_with_injections_v2': TimelineToJSON(value['threadedConversationWithInjectionsV2']),
    };
}

