/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TweetCardPlatform } from './TweetCardPlatform';
import {
    TweetCardPlatformFromJSON,
    TweetCardPlatformFromJSONTyped,
    TweetCardPlatformToJSON,
} from './TweetCardPlatform';

/**
 * 
 * @export
 * @interface TweetCardPlatformData
 */
export interface TweetCardPlatformData {
    /**
     * 
     * @type {TweetCardPlatform}
     * @memberof TweetCardPlatformData
     */
    platform: TweetCardPlatform;
}

/**
 * Check if a given object implements the TweetCardPlatformData interface.
 */
export function instanceOfTweetCardPlatformData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "platform" in value;

    return isInstance;
}

export function TweetCardPlatformDataFromJSON(json: any): TweetCardPlatformData {
    return TweetCardPlatformDataFromJSONTyped(json, false);
}

export function TweetCardPlatformDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TweetCardPlatformData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'platform': TweetCardPlatformFromJSON(json['platform']),
    };
}

export function TweetCardPlatformDataToJSON(value?: TweetCardPlatformData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'platform': TweetCardPlatformToJSON(value.platform),
    };
}

