/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Tweet,
    instanceOfTweet,
    TweetFromJSON,
    TweetFromJSONTyped,
    TweetToJSON,
} from './Tweet';
import {
    TweetTombstone,
    instanceOfTweetTombstone,
    TweetTombstoneFromJSON,
    TweetTombstoneFromJSONTyped,
    TweetTombstoneToJSON,
} from './TweetTombstone';
import {
    TweetWithVisibilityResults,
    instanceOfTweetWithVisibilityResults,
    TweetWithVisibilityResultsFromJSON,
    TweetWithVisibilityResultsFromJSONTyped,
    TweetWithVisibilityResultsToJSON,
} from './TweetWithVisibilityResults';

/**
 * @type TweetUnion
 * 
 * @export
 */
export type TweetUnion = Tweet | TweetTombstone | TweetWithVisibilityResults;

export function TweetUnionFromJSON(json: any): TweetUnion {
    return TweetUnionFromJSONTyped(json, false);
}

export function TweetUnionFromJSONTyped(json: any, ignoreDiscriminator: boolean): TweetUnion {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...TweetFromJSONTyped(json, true), ...TweetTombstoneFromJSONTyped(json, true), ...TweetWithVisibilityResultsFromJSONTyped(json, true) };
}

export function TweetUnionToJSON(value?: TweetUnion | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfTweet(value)) {
        return TweetToJSON(value as Tweet);
    }
    if (instanceOfTweetTombstone(value)) {
        return TweetTombstoneToJSON(value as TweetTombstone);
    }
    if (instanceOfTweetWithVisibilityResults(value)) {
        return TweetWithVisibilityResultsToJSON(value as TweetWithVisibilityResults);
    }

    return {};
}

