/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TweetInterstitialTextEntityRef
 */
export interface TweetInterstitialTextEntityRef {
    /**
     * 
     * @type {string}
     * @memberof TweetInterstitialTextEntityRef
     */
    type: TweetInterstitialTextEntityRefTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof TweetInterstitialTextEntityRef
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof TweetInterstitialTextEntityRef
     */
    urlType: TweetInterstitialTextEntityRefUrlTypeEnum;
}


/**
 * @export
 */
export const TweetInterstitialTextEntityRefTypeEnum = {
    TimelineUrl: 'TimelineUrl'
} as const;
export type TweetInterstitialTextEntityRefTypeEnum = typeof TweetInterstitialTextEntityRefTypeEnum[keyof typeof TweetInterstitialTextEntityRefTypeEnum];

/**
 * @export
 */
export const TweetInterstitialTextEntityRefUrlTypeEnum = {
    ExternalUrl: 'ExternalUrl'
} as const;
export type TweetInterstitialTextEntityRefUrlTypeEnum = typeof TweetInterstitialTextEntityRefUrlTypeEnum[keyof typeof TweetInterstitialTextEntityRefUrlTypeEnum];


/**
 * Check if a given object implements the TweetInterstitialTextEntityRef interface.
 */
export function instanceOfTweetInterstitialTextEntityRef(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "url" in value;
    isInstance = isInstance && "urlType" in value;

    return isInstance;
}

export function TweetInterstitialTextEntityRefFromJSON(json: any): TweetInterstitialTextEntityRef {
    return TweetInterstitialTextEntityRefFromJSONTyped(json, false);
}

export function TweetInterstitialTextEntityRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): TweetInterstitialTextEntityRef {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'url': json['url'],
        'urlType': json['urlType'],
    };
}

export function TweetInterstitialTextEntityRefToJSON(value?: TweetInterstitialTextEntityRef | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'url': value.url,
        'urlType': value.urlType,
    };
}

