/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TweetPreviewDisplayTweetViewCount
 */
export interface TweetPreviewDisplayTweetViewCount {
    /**
     * 
     * @type {string}
     * @memberof TweetPreviewDisplayTweetViewCount
     */
    count: string;
}

/**
 * Check if a given object implements the TweetPreviewDisplayTweetViewCount interface.
 */
export function instanceOfTweetPreviewDisplayTweetViewCount(value: object): value is TweetPreviewDisplayTweetViewCount {
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function TweetPreviewDisplayTweetViewCountFromJSON(json: any): TweetPreviewDisplayTweetViewCount {
    return TweetPreviewDisplayTweetViewCountFromJSONTyped(json, false);
}

export function TweetPreviewDisplayTweetViewCountFromJSONTyped(json: any, ignoreDiscriminator: boolean): TweetPreviewDisplayTweetViewCount {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
    };
}

export function TweetPreviewDisplayTweetViewCountToJSON(json: any): TweetPreviewDisplayTweetViewCount {
    return TweetPreviewDisplayTweetViewCountToJSONTyped(json, false);
}

export function TweetPreviewDisplayTweetViewCountToJSONTyped(value?: TweetPreviewDisplayTweetViewCount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
    };
}

