/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UnfavoriteTweet } from './UnfavoriteTweet';
import {
    UnfavoriteTweetFromJSON,
    UnfavoriteTweetFromJSONTyped,
    UnfavoriteTweetToJSON,
} from './UnfavoriteTweet';

/**
 * 
 * @export
 * @interface UnfavoriteTweetResponse
 */
export interface UnfavoriteTweetResponse {
    /**
     * 
     * @type {UnfavoriteTweet}
     * @memberof UnfavoriteTweetResponse
     */
    data: UnfavoriteTweet;
    /**
     * 
     * @type {Array<Error>}
     * @memberof UnfavoriteTweetResponse
     */
    errors?: Array<Error>;
}

/**
 * Check if a given object implements the UnfavoriteTweetResponse interface.
 */
export function instanceOfUnfavoriteTweetResponse(value: object): value is UnfavoriteTweetResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function UnfavoriteTweetResponseFromJSON(json: any): UnfavoriteTweetResponse {
    return UnfavoriteTweetResponseFromJSONTyped(json, false);
}

export function UnfavoriteTweetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnfavoriteTweetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': UnfavoriteTweetFromJSON(json['data']),
        'errors': json['errors'] == null ? undefined : json['errors'],
    };
}

export function UnfavoriteTweetResponseToJSON(value?: UnfavoriteTweetResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': UnfavoriteTweetToJSON(value['data']),
        'errors': value['errors'],
    };
}

