/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserTweetsResultV1 } from './UserTweetsResultV1';
import {
    UserTweetsResultV1FromJSON,
    UserTweetsResultV1FromJSONTyped,
    UserTweetsResultV1ToJSON,
    UserTweetsResultV1ToJSONTyped,
} from './UserTweetsResultV1';

/**
 * 
 * @export
 * @interface UserTweetsUser
 */
export interface UserTweetsUser {
    /**
     * 
     * @type {UserTweetsResultV1}
     * @memberof UserTweetsUser
     */
    result: UserTweetsResultV1;
}

/**
 * Check if a given object implements the UserTweetsUser interface.
 */
export function instanceOfUserTweetsUser(value: object): value is UserTweetsUser {
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function UserTweetsUserFromJSON(json: any): UserTweetsUser {
    return UserTweetsUserFromJSONTyped(json, false);
}

export function UserTweetsUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserTweetsUser {
    if (json == null) {
        return json;
    }
    return {
        
        'result': UserTweetsResultV1FromJSON(json['result']),
    };
}

export function UserTweetsUserToJSON(json: any): UserTweetsUser {
    return UserTweetsUserToJSONTyped(json, false);
}

export function UserTweetsUserToJSONTyped(value?: UserTweetsUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': UserTweetsResultV1ToJSON(value['result']),
    };
}

