/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserFeatures
 */
export interface UserFeatures {
    /**
     * 
     * @type {boolean}
     * @memberof UserFeatures
     */
    mediatoolStudioLibrary: boolean;
}

/**
 * Check if a given object implements the UserFeatures interface.
 */
export function instanceOfUserFeatures(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "mediatoolStudioLibrary" in value;

    return isInstance;
}

export function UserFeaturesFromJSON(json: any): UserFeatures {
    return UserFeaturesFromJSONTyped(json, false);
}

export function UserFeaturesFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserFeatures {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mediatoolStudioLibrary': json['mediatool_studio_library'],
    };
}

export function UserFeaturesToJSON(value?: UserFeatures | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mediatool_studio_library': value.mediatoolStudioLibrary,
    };
}

