/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserVerificationInfoReasonDescription } from './UserVerificationInfoReasonDescription';
import {
    UserVerificationInfoReasonDescriptionFromJSON,
    UserVerificationInfoReasonDescriptionFromJSONTyped,
    UserVerificationInfoReasonDescriptionToJSON,
} from './UserVerificationInfoReasonDescription';

/**
 * 
 * @export
 * @interface UserVerificationInfoReason
 */
export interface UserVerificationInfoReason {
    /**
     * 
     * @type {UserVerificationInfoReasonDescription}
     * @memberof UserVerificationInfoReason
     */
    description: UserVerificationInfoReasonDescription;
    /**
     * 
     * @type {number}
     * @memberof UserVerificationInfoReason
     */
    overrideVerifiedYear: number;
    /**
     * 
     * @type {string}
     * @memberof UserVerificationInfoReason
     */
    verifiedSinceMsec: string;
}

/**
 * Check if a given object implements the UserVerificationInfoReason interface.
 */
export function instanceOfUserVerificationInfoReason(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "overrideVerifiedYear" in value;
    isInstance = isInstance && "verifiedSinceMsec" in value;

    return isInstance;
}

export function UserVerificationInfoReasonFromJSON(json: any): UserVerificationInfoReason {
    return UserVerificationInfoReasonFromJSONTyped(json, false);
}

export function UserVerificationInfoReasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserVerificationInfoReason {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': UserVerificationInfoReasonDescriptionFromJSON(json['description']),
        'overrideVerifiedYear': json['override_verified_year'],
        'verifiedSinceMsec': json['verified_since_msec'],
    };
}

export function UserVerificationInfoReasonToJSON(value?: UserVerificationInfoReason | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': UserVerificationInfoReasonDescriptionToJSON(value.description),
        'override_verified_year': value.overrideVerifiedYear,
        'verified_since_msec': value.verifiedSinceMsec,
    };
}

