/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserResults } from './UserResults';
import {
    UserResultsFromJSON,
    UserResultsFromJSONTyped,
    UserResultsToJSON,
} from './UserResults';

/**
 * 
 * @export
 * @interface UserResponseData
 */
export interface UserResponseData {
    /**
     * 
     * @type {UserResults}
     * @memberof UserResponseData
     */
    user: UserResults;
}

/**
 * Check if a given object implements the UserResponseData interface.
 */
export function instanceOfUserResponseData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "user" in value;

    return isInstance;
}

export function UserResponseDataFromJSON(json: any): UserResponseData {
    return UserResponseDataFromJSONTyped(json, false);
}

export function UserResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': UserResultsFromJSON(json['user']),
    };
}

export function UserResponseDataToJSON(value?: UserResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': UserResultsToJSON(value.user),
    };
}

