/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateRetweetResponse,
  CreateTweetResponse,
  DeleteRetweetResponse,
  DeleteTweetResponse,
  FavoriteTweetResponseData,
  PostCreateRetweetRequest,
  PostCreateTweetRequest,
  PostDeleteRetweetRequest,
  PostDeleteTweetRequest,
  PostFavoriteTweetRequest,
  PostUnfavoriteTweetRequest,
  UnfavoriteTweetResponseData,
} from '../models';
import {
    CreateRetweetResponseFromJSON,
    CreateRetweetResponseToJSON,
    CreateTweetResponseFromJSON,
    CreateTweetResponseToJSON,
    DeleteRetweetResponseFromJSON,
    DeleteRetweetResponseToJSON,
    DeleteTweetResponseFromJSON,
    DeleteTweetResponseToJSON,
    FavoriteTweetResponseDataFromJSON,
    FavoriteTweetResponseDataToJSON,
    PostCreateRetweetRequestFromJSON,
    PostCreateRetweetRequestToJSON,
    PostCreateTweetRequestFromJSON,
    PostCreateTweetRequestToJSON,
    PostDeleteRetweetRequestFromJSON,
    PostDeleteRetweetRequestToJSON,
    PostDeleteTweetRequestFromJSON,
    PostDeleteTweetRequestToJSON,
    PostFavoriteTweetRequestFromJSON,
    PostFavoriteTweetRequestToJSON,
    PostUnfavoriteTweetRequestFromJSON,
    PostUnfavoriteTweetRequestToJSON,
    UnfavoriteTweetResponseDataFromJSON,
    UnfavoriteTweetResponseDataToJSON,
} from '../models';

export interface PostCreateRetweetOperationRequest {
    PostCreateRetweetRequest: PostCreateRetweetRequest;
}

export interface PostCreateTweetOperationRequest {
    PostCreateTweetRequest: PostCreateTweetRequest;
}

export interface PostDeleteRetweetOperationRequest {
    PostDeleteRetweetRequest: PostDeleteRetweetRequest;
}

export interface PostDeleteTweetOperationRequest {
    PostDeleteTweetRequest: PostDeleteTweetRequest;
}

export interface PostFavoriteTweetOperationRequest {
    PostFavoriteTweetRequest: PostFavoriteTweetRequest;
}

export interface PostUnfavoriteTweetOperationRequest {
    PostUnfavoriteTweetRequest: PostUnfavoriteTweetRequest;
}

/**
 * 
 */
export class PostApi extends runtime.BaseAPI {

    /**
     * create Retweet
     */
    async postCreateRetweetRaw(requestParameters: PostCreateRetweetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateRetweetResponse>> {
        if (requestParameters.PostCreateRetweetRequest === null || requestParameters.PostCreateRetweetRequest === undefined) {
            throw new runtime.RequiredError('PostCreateRetweetRequest','Required parameter requestParameters.PostCreateRetweetRequest was null or undefined when calling postCreateRetweet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-twitter-client-language"] = this.configuration.apiKey("x-twitter-client-language"); // ClientLanguage authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-twitter-active-user"] = this.configuration.apiKey("x-twitter-active-user"); // ActiveUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["user-agent"] = this.configuration.apiKey("user-agent"); // UserAgent authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-twitter-auth-type"] = this.configuration.apiKey("x-twitter-auth-type"); // AuthType authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-csrf-token"] = this.configuration.apiKey("x-csrf-token"); // CsrfToken authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/graphql/ojPdsZsimiJrUGLR1sjUtA/CreateRetweet`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostCreateRetweetRequestToJSON(requestParameters.PostCreateRetweetRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateRetweetResponseFromJSON(jsonValue));
    }

    /**
     * create Retweet
     */
    async postCreateRetweet(requestParameters: PostCreateRetweetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateRetweetResponse> {
        const response = await this.postCreateRetweetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * create Tweet
     */
    async postCreateTweetRaw(requestParameters: PostCreateTweetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateTweetResponse>> {
        if (requestParameters.PostCreateTweetRequest === null || requestParameters.PostCreateTweetRequest === undefined) {
            throw new runtime.RequiredError('PostCreateTweetRequest','Required parameter requestParameters.PostCreateTweetRequest was null or undefined when calling postCreateTweet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-twitter-client-language"] = this.configuration.apiKey("x-twitter-client-language"); // ClientLanguage authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-twitter-active-user"] = this.configuration.apiKey("x-twitter-active-user"); // ActiveUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["user-agent"] = this.configuration.apiKey("user-agent"); // UserAgent authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-twitter-auth-type"] = this.configuration.apiKey("x-twitter-auth-type"); // AuthType authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-csrf-token"] = this.configuration.apiKey("x-csrf-token"); // CsrfToken authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/graphql/1RyAhNwby-gzGCRVsMxKbQ/CreateTweet`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostCreateTweetRequestToJSON(requestParameters.PostCreateTweetRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateTweetResponseFromJSON(jsonValue));
    }

    /**
     * create Tweet
     */
    async postCreateTweet(requestParameters: PostCreateTweetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateTweetResponse> {
        const response = await this.postCreateTweetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * delete Retweet
     */
    async postDeleteRetweetRaw(requestParameters: PostDeleteRetweetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteRetweetResponse>> {
        if (requestParameters.PostDeleteRetweetRequest === null || requestParameters.PostDeleteRetweetRequest === undefined) {
            throw new runtime.RequiredError('PostDeleteRetweetRequest','Required parameter requestParameters.PostDeleteRetweetRequest was null or undefined when calling postDeleteRetweet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-twitter-client-language"] = this.configuration.apiKey("x-twitter-client-language"); // ClientLanguage authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-twitter-active-user"] = this.configuration.apiKey("x-twitter-active-user"); // ActiveUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["user-agent"] = this.configuration.apiKey("user-agent"); // UserAgent authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-twitter-auth-type"] = this.configuration.apiKey("x-twitter-auth-type"); // AuthType authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-csrf-token"] = this.configuration.apiKey("x-csrf-token"); // CsrfToken authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/graphql/iQtK4dl5hBmXewYZuEOKVw/DeleteRetweet`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostDeleteRetweetRequestToJSON(requestParameters.PostDeleteRetweetRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteRetweetResponseFromJSON(jsonValue));
    }

    /**
     * delete Retweet
     */
    async postDeleteRetweet(requestParameters: PostDeleteRetweetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteRetweetResponse> {
        const response = await this.postDeleteRetweetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * delete Retweet
     */
    async postDeleteTweetRaw(requestParameters: PostDeleteTweetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteTweetResponse>> {
        if (requestParameters.PostDeleteTweetRequest === null || requestParameters.PostDeleteTweetRequest === undefined) {
            throw new runtime.RequiredError('PostDeleteTweetRequest','Required parameter requestParameters.PostDeleteTweetRequest was null or undefined when calling postDeleteTweet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-twitter-client-language"] = this.configuration.apiKey("x-twitter-client-language"); // ClientLanguage authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-twitter-active-user"] = this.configuration.apiKey("x-twitter-active-user"); // ActiveUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["user-agent"] = this.configuration.apiKey("user-agent"); // UserAgent authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-twitter-auth-type"] = this.configuration.apiKey("x-twitter-auth-type"); // AuthType authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-csrf-token"] = this.configuration.apiKey("x-csrf-token"); // CsrfToken authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/graphql/VaenaVgh5q5ih7kvyVjgtg/DeleteTweet`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostDeleteTweetRequestToJSON(requestParameters.PostDeleteTweetRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteTweetResponseFromJSON(jsonValue));
    }

    /**
     * delete Retweet
     */
    async postDeleteTweet(requestParameters: PostDeleteTweetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteTweetResponse> {
        const response = await this.postDeleteTweetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * favorite Tweet
     */
    async postFavoriteTweetRaw(requestParameters: PostFavoriteTweetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FavoriteTweetResponseData>> {
        if (requestParameters.PostFavoriteTweetRequest === null || requestParameters.PostFavoriteTweetRequest === undefined) {
            throw new runtime.RequiredError('PostFavoriteTweetRequest','Required parameter requestParameters.PostFavoriteTweetRequest was null or undefined when calling postFavoriteTweet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-twitter-client-language"] = this.configuration.apiKey("x-twitter-client-language"); // ClientLanguage authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-twitter-active-user"] = this.configuration.apiKey("x-twitter-active-user"); // ActiveUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["user-agent"] = this.configuration.apiKey("user-agent"); // UserAgent authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-twitter-auth-type"] = this.configuration.apiKey("x-twitter-auth-type"); // AuthType authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-csrf-token"] = this.configuration.apiKey("x-csrf-token"); // CsrfToken authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/graphql/lI07N6Otwv1PhnEgXILM7A/FavoriteTweet`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostFavoriteTweetRequestToJSON(requestParameters.PostFavoriteTweetRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FavoriteTweetResponseDataFromJSON(jsonValue));
    }

    /**
     * favorite Tweet
     */
    async postFavoriteTweet(requestParameters: PostFavoriteTweetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FavoriteTweetResponseData> {
        const response = await this.postFavoriteTweetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * unfavorite Tweet
     */
    async postUnfavoriteTweetRaw(requestParameters: PostUnfavoriteTweetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UnfavoriteTweetResponseData>> {
        if (requestParameters.PostUnfavoriteTweetRequest === null || requestParameters.PostUnfavoriteTweetRequest === undefined) {
            throw new runtime.RequiredError('PostUnfavoriteTweetRequest','Required parameter requestParameters.PostUnfavoriteTweetRequest was null or undefined when calling postUnfavoriteTweet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-twitter-client-language"] = this.configuration.apiKey("x-twitter-client-language"); // ClientLanguage authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-twitter-active-user"] = this.configuration.apiKey("x-twitter-active-user"); // ActiveUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["user-agent"] = this.configuration.apiKey("user-agent"); // UserAgent authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-twitter-auth-type"] = this.configuration.apiKey("x-twitter-auth-type"); // AuthType authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-csrf-token"] = this.configuration.apiKey("x-csrf-token"); // CsrfToken authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/graphql/ZYKSe-w7KEslx3JhSIk5LA/UnfavoriteTweet`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostUnfavoriteTweetRequestToJSON(requestParameters.PostUnfavoriteTweetRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UnfavoriteTweetResponseDataFromJSON(jsonValue));
    }

    /**
     * unfavorite Tweet
     */
    async postUnfavoriteTweet(requestParameters: PostUnfavoriteTweetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UnfavoriteTweetResponseData> {
        const response = await this.postUnfavoriteTweetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
