inputSpec: twitter-openapi/dist/compatible/openapi-3.0.yaml
outputDir: .
npmName: twitter-openapi-typescript-generated
npmVersion: 0.0.37

# withoutRuntimeChecks: false
legacyDiscriminatorBehavior: false
# modelPropertyNaming: original
# stringEnums: true
# paramNaming: original
